#!/bin/bash
# =============================================================================
# DockerfileModifier.sh — Generate Dockerfile for vLLM CPU Docker image
# =============================================================================
# Reads build data from resources/build_data/ and generates a Dockerfile
# that builds a vLLM CPU inference image using docker/ scripts.
#
# Called by reusable-build-versions.yml during Docker image builds.
# =============================================================================

set -ex

REPO_NAME='vllm-cpu'
DOCKERFILE_NAME="Dockerfile.$REPO_NAME"

# Check for required build data
if [ ! -e ./resources/build_data/base-image ] || [ ! -e ./resources/build_data/version ]; then
    echo "Could not find required build data files. Exiting..."
    exit 1
fi

BASE_IMAGE=$(cat ./resources/build_data/base-image)
VLLM_VERSION=$(cat ./resources/build_data/version)

# Create a temporary file safely
TEMP_FILE=$(mktemp "${DOCKERFILE_NAME}.XXXXXX") || {
    echo "Error creating temporary file" >&2
    exit 1
}

# Write the Dockerfile content
{
    cat << EOF
# syntax=docker/dockerfile:1.9
# vLLM CPU Docker Image — Unified build (v0.17.0+)
# Auto-generated by DockerfileModifier.sh

ARG BASE_IMAGE=${BASE_IMAGE}
ARG VLLM_VERSION=${VLLM_VERSION}
ARG TARGETPLATFORM
ARG PYTHON_VERSION=auto
ARG USE_GITHUB_RELEASE=false

# ======================== Stage 1: Detect Python ========================
FROM \${BASE_IMAGE} AS python-detector

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt,sharing=locked \\
    apt-get update && apt-get install -y --no-install-recommends curl ca-certificates jq

ARG VLLM_VERSION
ARG PYTHON_VERSION
ARG USE_GITHUB_RELEASE

COPY docker/detect_python_version.sh /detect_python_version.sh
RUN --mount=type=secret,id=GITHUB_TOKEN,required=false \\
    chmod +x /detect_python_version.sh && \\
    export GITHUB_TOKEN=\$(cat /run/secrets/GITHUB_TOKEN 2>/dev/null || echo "") && \\
    /detect_python_version.sh "vllm-cpu" "\${VLLM_VERSION}" "\${PYTHON_VERSION}" "\${USE_GITHUB_RELEASE}"

# ======================== Stage 2: Runtime ========================
FROM \${BASE_IMAGE} AS runtime

COPY --from=python-detector /python_version.txt /tmp/python_version.txt

ARG VLLM_VERSION
ARG TARGETPLATFORM

# Install system dependencies
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt,sharing=locked \\
    apt-get update && apt-get install -y --no-install-recommends \\
    curl ca-certificates jq numactl libnuma-dev libtcmalloc-minimal4 \\
    build-essential procps net-tools && \\
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:\${PATH}"

# Create vLLM directory structure
WORKDIR /vllm
RUN mkdir -p /vllm/docker /data

# Copy scripts
COPY docker/setup_vllm.sh /vllm/docker/setup_vllm.sh
COPY docker/entrypoint.sh /vllm/docker/entrypoint.sh
COPY docker/cleanup.sh /vllm/docker/cleanup.sh
COPY docker/banner.sh /vllm/docker/banner.sh
RUN chmod +x /vllm/docker/*.sh

# Install Python + vLLM
RUN --mount=type=cache,target=/root/.cache/uv \\
    /vllm/docker/setup_vllm.sh "noavx512" "\${VLLM_VERSION}" "false"

# Cleanup to reduce image size
RUN /vllm/docker/cleanup.sh

# Environment defaults
ENV VLLM_TARGET_DEVICE=cpu
ENV VLLM_SERVER_HOST=0.0.0.0
ENV VLLM_SERVER_PORT=8000
ENV VLLM_DTYPE=bfloat16
ENV MALLOC_TRIM_THRESHOLD_=100000
ENV DATA_DIR=/data

# LD_PRELOAD for tcmalloc (auto-detected by entrypoint)
# Expose API port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=120s --retries=5 \\
    CMD curl -f http://localhost:\${VLLM_SERVER_PORT:-8000}/health || exit 1

ENTRYPOINT ["/vllm/docker/entrypoint.sh"]
EOF
} > "$TEMP_FILE"

# Atomically replace the target file
if mv -f "$TEMP_FILE" "$DOCKERFILE_NAME"; then
    echo "Dockerfile generation completed!"
    echo "######      DOCKERFILE START     ######"
    cat "$DOCKERFILE_NAME"
    echo "######      DOCKERFILE END     ######"
else
    echo "Error: Failed to create Dockerfile for $REPO_NAME" >&2
    rm -f "$TEMP_FILE"
    exit 1
fi
