# =============================================================================
# Composite Action: Setup Build Environment
# =============================================================================
# Consolidates common build setup steps:
# - Environment preparation
# - Disk space cleanup
# - System dependencies installation
# - UV package manager setup
# - ccache configuration
#
# Usage:
#   - uses: ./.github/actions/setup-build-env
#     with:
#       platform: amd64
#       variant: noavx512
#       version: "0.12.0"
# =============================================================================

name: 'Setup Build Environment'
description: 'Install system dependencies, setup uv, and configure ccache for vLLM CPU wheel builds'

inputs:
  uv_version:
    description: 'UV package manager version'
    required: false
    default: '0.5'
  platform:
    description: 'Target platform (amd64, arm64) - used for cache key'
    required: true
  variant:
    description: 'Build variant (noavx512, avx512, etc.) - used for cache key'
    required: true
  version:
    description: 'vLLM version - used for cache key'
    required: true

outputs:
  cache-hit:
    description: 'Whether ccache was restored from cache'
    value: ${{ steps.ccache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      shell: bash
      run: |
        # Ensure all shell scripts are executable
        find . -name "*.sh" -type f -exec chmod +x {} \;
        # Create required directories
        mkdir -p dist
        mkdir -p ~/.cache/ccache

    - name: Free disk space
      shell: bash
      run: |
        # Remove unnecessary large packages to free disk space
        # These are pre-installed on GitHub runners but not needed for our builds
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc 2>/dev/null || true
        df -h

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          python3 python3-pip python3-venv \
          build-essential gcc g++ \
          cmake ninja-build ccache \
          libnuma-dev numactl jq

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv_version }}
        # Disable uv's built-in cache to avoid "cache path does not exist" errors
        # when builds don't use uv extensively. We rely on ccache for build caching.
        enable-cache: false

    - name: Cache ccache
      id: ccache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ inputs.platform }}-${{ inputs.variant }}-${{ inputs.version }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ inputs.platform }}-${{ inputs.variant }}-${{ inputs.version }}-
          ccache-${{ inputs.platform }}-${{ inputs.variant }}-
          ccache-${{ inputs.platform }}-

    - name: Show ccache stats
      shell: bash
      run: |
        echo "=== ccache configuration ==="
        ccache --show-config 2>/dev/null || true
        echo ""
        echo "=== ccache statistics ==="
        ccache --show-stats 2>/dev/null || true
